### ISSUE TITLE
 Feature: Implement html2canvas to save the diagram to a image

### ISSUE THREAD

**Issue by CsarChvz** [Ovyerus/prismaliser#76] opened 2023-11-14 00:19 UTC
Add a button to save the diagram into a image

**Comment by Ovyerus** [comment] 2023-11-14 01:59
Duplicate of #26

**Closed by Ovyerus** 2023-11-14 01:59 UTC

**Comment by sharifmrahat** [comment] 2023-11-17 19:22
Download diagram option is not available. Can follow the react-follow docs: https://reactflow.dev/examples/misc/download-image

**Comment by Ovyerus** [comment] 2023-11-21 22:54
This is now implemented as of 3758d6fbe30ac20b99be50f13e4ebf79d266e521
